package views;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import main.MainClass;
import models.Car;
import models.ObjectFormType;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import services.implementation.CarSaverLoaderService;
import services.implementation.ObjectFormService;

public class ListObjectsForm extends javax.swing.JFrame {

    JSONArray cars;
    ObjectFormService objectService;
    CarSaverLoaderService carService;

    /**
     * Creates new form ListObjectsForm
     */
    private ListObjectsForm() {
        initComponents();
    }

    public ListObjectsForm(ObjectFormService objectService, CarSaverLoaderService carService) {
        initComponents();
        this.objectService = objectService;
        this.carService = carService;
    }

    public void update(JSONArray cars) {
        this.cars = cars;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (int i = 0; i < cars.size(); i++) {
            JSONObject car = (JSONObject) cars.get(i);
            model.addRow(new Object[]{
                car.get("model"),
                car.get("maxSpeed"),
                car.get("isElectric"),
                car.get("id")
            }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Viteza maxima", "Electrica", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click pe un rand din tabel pentru a edita/sterge o masina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int selectedTabelIndex = jTable1.getSelectedRow();
            if (selectedTabelIndex != -1) {
                JPopupMenu pop = new JPopupMenu();
                Car selectedCar = new Car((JSONObject) cars.get(selectedTabelIndex));
                pop.setSize(300, 100);
                pop.setLocation(evt.getXOnScreen(), evt.getYOnScreen());
                JButton editButton = new JButton("Modifica");
                JButton deleteButton = new JButton("Sterge");
                editButton.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        ObjectForm objectForm = new ObjectForm(ObjectFormType.ModifyCar, objectService, selectedCar);
                        objectForm.setVisible(true);
                        pop.setVisible(false);
                    }
                });
                deleteButton.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            carService.removeCarFromDatabase(selectedCar, MainClass.MASINI_FILE);
                        } catch (IOException | ClassNotFoundException ex) {
                            Logger.getLogger(ListObjectsForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        pop.setVisible(false);
                    }
                });
                pop.add(editButton);
                pop.add(deleteButton);
                pop.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        if (evt.getX() >= pop.getWidth() || evt.getY() >= pop.getHeight() || evt.getX() <= 0 || evt.getY() <= 0) {
                            pop.setVisible(false);
                        }
                    }
                });
                pop.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        MainClass.ROOT_REF.mainMenu.setEnabled(true);
        MainClass.ROOT_REF.mainMenu.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
